### ISSUE TITLE
 An error occurred contacting the server.

### ISSUE THREAD

**Issue by kohlkopf** [MG-RAST/MG-RASTv4#385]
![Screen Shot 2020-01-02 at 9 14 05 AM](https://user-images.githubusercontent.com/28633777/71677630-8d4cd100-2d40-11ea-9af8-586c061d7577.png)
 
I have been met with this screen for the past several days. I can not upload any files. Is this issue specific to me? The problems began after I attempted to upload close to one hundred files--maybe my problems are related to that.

**Comment by folker** [comment]
Please contact our help desk..
